### ISSUE TITLE
here doc historique

### ISSUE THREAD

**Issue by ecogest** [Anysiia/minishell#6]
Comportement souhaité:
	- lorsqu'une commande avec un HERE-doc a été rentrée précédemment, on devrait pouvoir la récupérer intégralement dans l'historique (flèches clavier) -> (ce que bash fait)

Comportement observé:
	- seule la première ligne de la commande est affichée

Mon avis: Je ne pense pas qu'il faille se prendre la tête et gérer ça, d'autant que je n'ai pas la moindre idée du "comment"... Mais bon je le mentionne au cas où quand même !

**Comment by Anysiia** [comment]
"“<<” read input from the current source until a line containing only the de-
limiter is seen. it doesn’t need to update history!"

Le sujet precise bien qu'on a pas a gerer l'historique
